//swiftlint:disable force_unwrapping

// swiftlint:disable file_length
// swiftlint:disable line_length

public enum Images {

}

// autogenerated with SwiftGen
// DO NOT EDIT

extension Images {
        public enum EventFilters {
        public static var date : UIImage { return Bundle.core.image(named: "date")! }
        public static var prizePool : UIImage { return Bundle.core.image(named: "prize_pool")! }
        public static var teams : UIImage { return Bundle.core.image(named: "teams")! }
        }
        public enum Events {
        public static var filter : UIImage { return Bundle.core.image(named: "filter")! }
        public static var refresh : UIImage { return Bundle.core.image(named: "refresh")! }
        }
        public enum General {
        public static var darkBack : UIImage { return Bundle.core.image(named: "dark_back")! }
        public static var details : UIImage { return Bundle.core.image(named: "details")! }
        public static var error : UIImage { return Bundle.core.image(named: "error")! }
        public static var lightBack : UIImage { return Bundle.core.image(named: "light_back")! }
        public static var lightClose : UIImage { return Bundle.core.image(named: "light_close")! }
        public static var message : UIImage { return Bundle.core.image(named: "message")! }
        public static var more : UIImage { return Bundle.core.image(named: "more")! }
        public static var share : UIImage { return Bundle.core.image(named: "share")! }
        public static var themeBack : UIImage { return Bundle.core.image(named: "theme_back")! }
        public static var themeClose : UIImage { return Bundle.core.image(named: "theme_close")! }
        }
        public enum ImageViewer {
        public static var browser : UIImage { return Bundle.core.image(named: "browser")! }
        public static var save : UIImage { return Bundle.core.image(named: "save")! }
        }
        public enum PlayerDescription {
        public static var profileHeaderBackground : UIImage { return Bundle.core.image(named: "profile_header_background")! }
        }
        public enum Profile {
        public static var donate : UIImage { return Bundle.core.image(named: "donate")! }
        public static var email : UIImage { return Bundle.core.image(named: "email")! }
        public static var feedback : UIImage { return Bundle.core.image(named: "feedback")! }
        public static var profileBig : UIImage { return Bundle.core.image(named: "profile_big")! }
        public static var rate : UIImage { return Bundle.core.image(named: "rate")! }
        public static var skins : UIImage { return Bundle.core.image(named: "skins")! }
        public static var storage : UIImage { return Bundle.core.image(named: "storage")! }
        }
        public enum Sections {
        public static var eventsDeselected : UIImage { return Bundle.core.image(named: "events_deselected")! }
        public static var eventsSelected : UIImage { return Bundle.core.image(named: "events_selected")! }
        public static var newsDeselected : UIImage { return Bundle.core.image(named: "news_deselected")! }
        public static var newsSelected : UIImage { return Bundle.core.image(named: "news_selected")! }
        public static var playersDeselected : UIImage { return Bundle.core.image(named: "players_deselected")! }
        public static var playersSelected : UIImage { return Bundle.core.image(named: "players_selected")! }
        public static var profileDeselected : UIImage { return Bundle.core.image(named: "profile_deselected")! }
        public static var profileSelected : UIImage { return Bundle.core.image(named: "profile_selected")! }
        public static var teamsDeselected : UIImage { return Bundle.core.image(named: "teams_deselected")! }
        public static var teamsSelected : UIImage { return Bundle.core.image(named: "teams_selected")! }
        }
        public enum Tutorial {
        public static var tutorial1 : UIImage { return Bundle.core.image(named: "tutorial1")! }
        public static var tutorial2 : UIImage { return Bundle.core.image(named: "tutorial2")! }
        public static var tutorial3 : UIImage { return Bundle.core.image(named: "tutorial3")! }
        public static var tutorial4 : UIImage { return Bundle.core.image(named: "tutorial4")! }
        public static var tutorial5 : UIImage { return Bundle.core.image(named: "tutorial5")! }
        }
}
