import XCTest
import Core
import AppRouter
import TestsHelper

// additional tests can be found in autogenerated RouterTestsGenerated.swift
class RouterTests: XCTestCase {
    var container: DependencyContainer!
    var router: Router!
    
    override func setUp() {
        super.setUp()
        container = DependencyContainer().registerAll().stubStorages()
        router = Router(router: AppRouter.shared, viewFactory: container, viewModelFactory: container)
    }
}
